// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCommonImage = "common_images"

// CommonImage mapped from table <common_images>
type CommonImage struct {
	ID         *string    `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	FileName   string     `gorm:"column:file_name;type:text;not null" json:"file_name"`
	FilePath   string     `gorm:"column:file_path;type:text;not null" json:"file_path"`
	MimeType   string     `gorm:"column:mime_type;type:text;not null" json:"mime_type"`
	FileSize   int64      `gorm:"column:file_size;type:bigint;not null" json:"file_size"`
	UploadedAt *time.Time `gorm:"column:uploaded_at;type:timestamp with time zone;not null;default:now()" json:"uploaded_at"`
}

// TableName CommonImage's table name
func (*CommonImage) TableName() string {
	return TableNameCommonImage
}
