// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameIsirmtWorkClick = "isirmt_work_clicks"

// IsirmtWorkClick mapped from table <isirmt_work_clicks>
type IsirmtWorkClick struct {
	ID        *string    `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	WorkID    string     `gorm:"column:work_id;type:uuid;not null;index:idx_isirmt_work_clicks_work_id,priority:1" json:"work_id"`
	ClickedAt *time.Time `gorm:"column:clicked_at;type:timestamp with time zone;not null;index:idx_isirmt_work_clicks_clicked_at,priority:1;default:now()" json:"clicked_at"`
}

// TableName IsirmtWorkClick's table name
func (*IsirmtWorkClick) TableName() string {
	return TableNameIsirmtWorkClick
}
