// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameIsirmtWorkImage = "isirmt_work_images"

// IsirmtWorkImage mapped from table <isirmt_work_images>
type IsirmtWorkImage struct {
	ID           *string `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	WorkID       string  `gorm:"column:work_id;type:uuid;not null" json:"work_id"`
	ImageID      string  `gorm:"column:image_id;type:uuid;not null" json:"image_id"`
	DisplayOrder int32   `gorm:"column:display_order;type:integer;not null" json:"display_order"`
}

// TableName IsirmtWorkImage's table name
func (*IsirmtWorkImage) TableName() string {
	return TableNameIsirmtWorkImage
}
