// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameIsirmtWorkTechStack = "isirmt_work_tech_stacks"

// IsirmtWorkTechStack mapped from table <isirmt_work_tech_stacks>
type IsirmtWorkTechStack struct {
	ID          *string `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	WorkID      string  `gorm:"column:work_id;type:uuid;not null" json:"work_id"`
	TechStackID string  `gorm:"column:tech_stack_id;type:uuid;not null" json:"tech_stack_id"`
}

// TableName IsirmtWorkTechStack's table name
func (*IsirmtWorkTechStack) TableName() string {
	return TableNameIsirmtWorkTechStack
}
