services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pg_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      HOSTNAME: "0.0.0.0"
      PORT: "3000"
      DATABASE_URL: "postgresql://app:app_password@db:5432/appdb"
    volumes:
      - ./frontend:/app
      - node_modules_dev:/app/node_modules
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_dev:
  node_modules_dev:
