services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pg_dev:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    environment:
      NODE_ENV: development
      HOSTNAME: "0.0.0.0"
      PORT: "3000"
      DATABASE_URL: "postgresql://app:app_password@db:5432/appdb"
      ADMIN_SECRET: ${ADMIN_SECRET}
    volumes:
      - ./frontend:/app
      - node_modules_dev:/app/node_modules
    depends_on:
      db:
        condition: service_healthy

  backend:
    image: golang:1.23-bookworm
    working_dir: /app
    command:
      [
        "bash",
        "-c",
        "go mod download && go install github.com/air-verse/air@v1.52.3 && air -c .air.toml",
      ]
    environment:
      DATABASE_URL: "postgres://app:app_password@db:5432/appdb"
      ALLOWED_ORIGIN: "http://localhost:3000"
      ADMIN_SECRET: ${ADMIN_SECRET}
    volumes:
      - ./backend:/app
      - go_mod_cache:/go/pkg/mod
      - ./uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer:4
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      db:
        condition: service_healthy

  caddy:
    image: caddy:2
    ports:
      - "3000:3000"
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
    depends_on:
      web:
        condition: service_started
      backend:
        condition: service_started

volumes:
  pg_dev:
  node_modules_dev:
  go_mod_cache:
