// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"realtime/internal/query/model"
)

func newCommonTechStack(db *gorm.DB, opts ...gen.DOOption) commonTechStack {
	_commonTechStack := commonTechStack{}

	_commonTechStack.commonTechStackDo.UseDB(db, opts...)
	_commonTechStack.commonTechStackDo.UseModel(&model.CommonTechStack{})

	tableName := _commonTechStack.commonTechStackDo.TableName()
	_commonTechStack.ALL = field.NewAsterisk(tableName)
	_commonTechStack.ID = field.NewString(tableName, "id")
	_commonTechStack.Name = field.NewString(tableName, "name")

	_commonTechStack.fillFieldMap()

	return _commonTechStack
}

type commonTechStack struct {
	commonTechStackDo commonTechStackDo

	ALL  field.Asterisk
	ID   field.String
	Name field.String

	fieldMap map[string]field.Expr
}

func (c commonTechStack) Table(newTableName string) *commonTechStack {
	c.commonTechStackDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c commonTechStack) As(alias string) *commonTechStack {
	c.commonTechStackDo.DO = *(c.commonTechStackDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *commonTechStack) updateTableName(table string) *commonTechStack {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewString(table, "id")
	c.Name = field.NewString(table, "name")

	c.fillFieldMap()

	return c
}

func (c *commonTechStack) WithContext(ctx context.Context) ICommonTechStackDo {
	return c.commonTechStackDo.WithContext(ctx)
}

func (c commonTechStack) TableName() string { return c.commonTechStackDo.TableName() }

func (c commonTechStack) Alias() string { return c.commonTechStackDo.Alias() }

func (c commonTechStack) Columns(cols ...field.Expr) gen.Columns {
	return c.commonTechStackDo.Columns(cols...)
}

func (c *commonTechStack) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *commonTechStack) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 2)
	c.fieldMap["id"] = c.ID
	c.fieldMap["name"] = c.Name
}

func (c commonTechStack) clone(db *gorm.DB) commonTechStack {
	c.commonTechStackDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c commonTechStack) replaceDB(db *gorm.DB) commonTechStack {
	c.commonTechStackDo.ReplaceDB(db)
	return c
}

type commonTechStackDo struct{ gen.DO }

type ICommonTechStackDo interface {
	gen.SubQuery
	Debug() ICommonTechStackDo
	WithContext(ctx context.Context) ICommonTechStackDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICommonTechStackDo
	WriteDB() ICommonTechStackDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICommonTechStackDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICommonTechStackDo
	Not(conds ...gen.Condition) ICommonTechStackDo
	Or(conds ...gen.Condition) ICommonTechStackDo
	Select(conds ...field.Expr) ICommonTechStackDo
	Where(conds ...gen.Condition) ICommonTechStackDo
	Order(conds ...field.Expr) ICommonTechStackDo
	Distinct(cols ...field.Expr) ICommonTechStackDo
	Omit(cols ...field.Expr) ICommonTechStackDo
	Join(table schema.Tabler, on ...field.Expr) ICommonTechStackDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICommonTechStackDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICommonTechStackDo
	Group(cols ...field.Expr) ICommonTechStackDo
	Having(conds ...gen.Condition) ICommonTechStackDo
	Limit(limit int) ICommonTechStackDo
	Offset(offset int) ICommonTechStackDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICommonTechStackDo
	Unscoped() ICommonTechStackDo
	Create(values ...*model.CommonTechStack) error
	CreateInBatches(values []*model.CommonTechStack, batchSize int) error
	Save(values ...*model.CommonTechStack) error
	First() (*model.CommonTechStack, error)
	Take() (*model.CommonTechStack, error)
	Last() (*model.CommonTechStack, error)
	Find() ([]*model.CommonTechStack, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CommonTechStack, err error)
	FindInBatches(result *[]*model.CommonTechStack, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CommonTechStack) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICommonTechStackDo
	Assign(attrs ...field.AssignExpr) ICommonTechStackDo
	Joins(fields ...field.RelationField) ICommonTechStackDo
	Preload(fields ...field.RelationField) ICommonTechStackDo
	FirstOrInit() (*model.CommonTechStack, error)
	FirstOrCreate() (*model.CommonTechStack, error)
	FindByPage(offset int, limit int) (result []*model.CommonTechStack, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICommonTechStackDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c commonTechStackDo) Debug() ICommonTechStackDo {
	return c.withDO(c.DO.Debug())
}

func (c commonTechStackDo) WithContext(ctx context.Context) ICommonTechStackDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c commonTechStackDo) ReadDB() ICommonTechStackDo {
	return c.Clauses(dbresolver.Read)
}

func (c commonTechStackDo) WriteDB() ICommonTechStackDo {
	return c.Clauses(dbresolver.Write)
}

func (c commonTechStackDo) Session(config *gorm.Session) ICommonTechStackDo {
	return c.withDO(c.DO.Session(config))
}

func (c commonTechStackDo) Clauses(conds ...clause.Expression) ICommonTechStackDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c commonTechStackDo) Returning(value interface{}, columns ...string) ICommonTechStackDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c commonTechStackDo) Not(conds ...gen.Condition) ICommonTechStackDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c commonTechStackDo) Or(conds ...gen.Condition) ICommonTechStackDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c commonTechStackDo) Select(conds ...field.Expr) ICommonTechStackDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c commonTechStackDo) Where(conds ...gen.Condition) ICommonTechStackDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c commonTechStackDo) Order(conds ...field.Expr) ICommonTechStackDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c commonTechStackDo) Distinct(cols ...field.Expr) ICommonTechStackDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c commonTechStackDo) Omit(cols ...field.Expr) ICommonTechStackDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c commonTechStackDo) Join(table schema.Tabler, on ...field.Expr) ICommonTechStackDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c commonTechStackDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICommonTechStackDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c commonTechStackDo) RightJoin(table schema.Tabler, on ...field.Expr) ICommonTechStackDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c commonTechStackDo) Group(cols ...field.Expr) ICommonTechStackDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c commonTechStackDo) Having(conds ...gen.Condition) ICommonTechStackDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c commonTechStackDo) Limit(limit int) ICommonTechStackDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c commonTechStackDo) Offset(offset int) ICommonTechStackDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c commonTechStackDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICommonTechStackDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c commonTechStackDo) Unscoped() ICommonTechStackDo {
	return c.withDO(c.DO.Unscoped())
}

func (c commonTechStackDo) Create(values ...*model.CommonTechStack) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c commonTechStackDo) CreateInBatches(values []*model.CommonTechStack, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c commonTechStackDo) Save(values ...*model.CommonTechStack) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c commonTechStackDo) First() (*model.CommonTechStack, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommonTechStack), nil
	}
}

func (c commonTechStackDo) Take() (*model.CommonTechStack, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommonTechStack), nil
	}
}

func (c commonTechStackDo) Last() (*model.CommonTechStack, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommonTechStack), nil
	}
}

func (c commonTechStackDo) Find() ([]*model.CommonTechStack, error) {
	result, err := c.DO.Find()
	return result.([]*model.CommonTechStack), err
}

func (c commonTechStackDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CommonTechStack, err error) {
	buf := make([]*model.CommonTechStack, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c commonTechStackDo) FindInBatches(result *[]*model.CommonTechStack, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c commonTechStackDo) Attrs(attrs ...field.AssignExpr) ICommonTechStackDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c commonTechStackDo) Assign(attrs ...field.AssignExpr) ICommonTechStackDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c commonTechStackDo) Joins(fields ...field.RelationField) ICommonTechStackDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c commonTechStackDo) Preload(fields ...field.RelationField) ICommonTechStackDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c commonTechStackDo) FirstOrInit() (*model.CommonTechStack, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommonTechStack), nil
	}
}

func (c commonTechStackDo) FirstOrCreate() (*model.CommonTechStack, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommonTechStack), nil
	}
}

func (c commonTechStackDo) FindByPage(offset int, limit int) (result []*model.CommonTechStack, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c commonTechStackDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c commonTechStackDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c commonTechStackDo) Delete(models ...*model.CommonTechStack) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *commonTechStackDo) withDO(do gen.Dao) *commonTechStackDo {
	c.DO = *do.(*gen.DO)
	return c
}
