// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"realtime/internal/query/model"
)

func newCommonImage(db *gorm.DB, opts ...gen.DOOption) commonImage {
	_commonImage := commonImage{}

	_commonImage.commonImageDo.UseDB(db, opts...)
	_commonImage.commonImageDo.UseModel(&model.CommonImage{})

	tableName := _commonImage.commonImageDo.TableName()
	_commonImage.ALL = field.NewAsterisk(tableName)
	_commonImage.ID = field.NewString(tableName, "id")
	_commonImage.FileName = field.NewString(tableName, "file_name")
	_commonImage.FilePath = field.NewString(tableName, "file_path")
	_commonImage.MimeType = field.NewString(tableName, "mime_type")
	_commonImage.FileSize = field.NewInt64(tableName, "file_size")
	_commonImage.UploadedAt = field.NewTime(tableName, "uploaded_at")

	_commonImage.fillFieldMap()

	return _commonImage
}

type commonImage struct {
	commonImageDo commonImageDo

	ALL        field.Asterisk
	ID         field.String
	FileName   field.String
	FilePath   field.String
	MimeType   field.String
	FileSize   field.Int64
	UploadedAt field.Time

	fieldMap map[string]field.Expr
}

func (c commonImage) Table(newTableName string) *commonImage {
	c.commonImageDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c commonImage) As(alias string) *commonImage {
	c.commonImageDo.DO = *(c.commonImageDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *commonImage) updateTableName(table string) *commonImage {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewString(table, "id")
	c.FileName = field.NewString(table, "file_name")
	c.FilePath = field.NewString(table, "file_path")
	c.MimeType = field.NewString(table, "mime_type")
	c.FileSize = field.NewInt64(table, "file_size")
	c.UploadedAt = field.NewTime(table, "uploaded_at")

	c.fillFieldMap()

	return c
}

func (c *commonImage) WithContext(ctx context.Context) ICommonImageDo {
	return c.commonImageDo.WithContext(ctx)
}

func (c commonImage) TableName() string { return c.commonImageDo.TableName() }

func (c commonImage) Alias() string { return c.commonImageDo.Alias() }

func (c commonImage) Columns(cols ...field.Expr) gen.Columns { return c.commonImageDo.Columns(cols...) }

func (c *commonImage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *commonImage) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 6)
	c.fieldMap["id"] = c.ID
	c.fieldMap["file_name"] = c.FileName
	c.fieldMap["file_path"] = c.FilePath
	c.fieldMap["mime_type"] = c.MimeType
	c.fieldMap["file_size"] = c.FileSize
	c.fieldMap["uploaded_at"] = c.UploadedAt
}

func (c commonImage) clone(db *gorm.DB) commonImage {
	c.commonImageDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c commonImage) replaceDB(db *gorm.DB) commonImage {
	c.commonImageDo.ReplaceDB(db)
	return c
}

type commonImageDo struct{ gen.DO }

type ICommonImageDo interface {
	gen.SubQuery
	Debug() ICommonImageDo
	WithContext(ctx context.Context) ICommonImageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICommonImageDo
	WriteDB() ICommonImageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICommonImageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICommonImageDo
	Not(conds ...gen.Condition) ICommonImageDo
	Or(conds ...gen.Condition) ICommonImageDo
	Select(conds ...field.Expr) ICommonImageDo
	Where(conds ...gen.Condition) ICommonImageDo
	Order(conds ...field.Expr) ICommonImageDo
	Distinct(cols ...field.Expr) ICommonImageDo
	Omit(cols ...field.Expr) ICommonImageDo
	Join(table schema.Tabler, on ...field.Expr) ICommonImageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICommonImageDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICommonImageDo
	Group(cols ...field.Expr) ICommonImageDo
	Having(conds ...gen.Condition) ICommonImageDo
	Limit(limit int) ICommonImageDo
	Offset(offset int) ICommonImageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICommonImageDo
	Unscoped() ICommonImageDo
	Create(values ...*model.CommonImage) error
	CreateInBatches(values []*model.CommonImage, batchSize int) error
	Save(values ...*model.CommonImage) error
	First() (*model.CommonImage, error)
	Take() (*model.CommonImage, error)
	Last() (*model.CommonImage, error)
	Find() ([]*model.CommonImage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CommonImage, err error)
	FindInBatches(result *[]*model.CommonImage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CommonImage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICommonImageDo
	Assign(attrs ...field.AssignExpr) ICommonImageDo
	Joins(fields ...field.RelationField) ICommonImageDo
	Preload(fields ...field.RelationField) ICommonImageDo
	FirstOrInit() (*model.CommonImage, error)
	FirstOrCreate() (*model.CommonImage, error)
	FindByPage(offset int, limit int) (result []*model.CommonImage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICommonImageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c commonImageDo) Debug() ICommonImageDo {
	return c.withDO(c.DO.Debug())
}

func (c commonImageDo) WithContext(ctx context.Context) ICommonImageDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c commonImageDo) ReadDB() ICommonImageDo {
	return c.Clauses(dbresolver.Read)
}

func (c commonImageDo) WriteDB() ICommonImageDo {
	return c.Clauses(dbresolver.Write)
}

func (c commonImageDo) Session(config *gorm.Session) ICommonImageDo {
	return c.withDO(c.DO.Session(config))
}

func (c commonImageDo) Clauses(conds ...clause.Expression) ICommonImageDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c commonImageDo) Returning(value interface{}, columns ...string) ICommonImageDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c commonImageDo) Not(conds ...gen.Condition) ICommonImageDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c commonImageDo) Or(conds ...gen.Condition) ICommonImageDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c commonImageDo) Select(conds ...field.Expr) ICommonImageDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c commonImageDo) Where(conds ...gen.Condition) ICommonImageDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c commonImageDo) Order(conds ...field.Expr) ICommonImageDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c commonImageDo) Distinct(cols ...field.Expr) ICommonImageDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c commonImageDo) Omit(cols ...field.Expr) ICommonImageDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c commonImageDo) Join(table schema.Tabler, on ...field.Expr) ICommonImageDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c commonImageDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICommonImageDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c commonImageDo) RightJoin(table schema.Tabler, on ...field.Expr) ICommonImageDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c commonImageDo) Group(cols ...field.Expr) ICommonImageDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c commonImageDo) Having(conds ...gen.Condition) ICommonImageDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c commonImageDo) Limit(limit int) ICommonImageDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c commonImageDo) Offset(offset int) ICommonImageDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c commonImageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICommonImageDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c commonImageDo) Unscoped() ICommonImageDo {
	return c.withDO(c.DO.Unscoped())
}

func (c commonImageDo) Create(values ...*model.CommonImage) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c commonImageDo) CreateInBatches(values []*model.CommonImage, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c commonImageDo) Save(values ...*model.CommonImage) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c commonImageDo) First() (*model.CommonImage, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommonImage), nil
	}
}

func (c commonImageDo) Take() (*model.CommonImage, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommonImage), nil
	}
}

func (c commonImageDo) Last() (*model.CommonImage, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommonImage), nil
	}
}

func (c commonImageDo) Find() ([]*model.CommonImage, error) {
	result, err := c.DO.Find()
	return result.([]*model.CommonImage), err
}

func (c commonImageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CommonImage, err error) {
	buf := make([]*model.CommonImage, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c commonImageDo) FindInBatches(result *[]*model.CommonImage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c commonImageDo) Attrs(attrs ...field.AssignExpr) ICommonImageDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c commonImageDo) Assign(attrs ...field.AssignExpr) ICommonImageDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c commonImageDo) Joins(fields ...field.RelationField) ICommonImageDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c commonImageDo) Preload(fields ...field.RelationField) ICommonImageDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c commonImageDo) FirstOrInit() (*model.CommonImage, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommonImage), nil
	}
}

func (c commonImageDo) FirstOrCreate() (*model.CommonImage, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommonImage), nil
	}
}

func (c commonImageDo) FindByPage(offset int, limit int) (result []*model.CommonImage, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c commonImageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c commonImageDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c commonImageDo) Delete(models ...*model.CommonImage) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *commonImageDo) withDO(do gen.Dao) *commonImageDo {
	c.DO = *do.(*gen.DO)
	return c
}
