// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                   = new(Query)
	CommonImage         *commonImage
	CommonTechStack     *commonTechStack
	IsirmtWork          *isirmtWork
	IsirmtWorkClick     *isirmtWorkClick
	IsirmtWorkImage     *isirmtWorkImage
	IsirmtWorkTechStack *isirmtWorkTechStack
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	CommonImage = &Q.CommonImage
	CommonTechStack = &Q.CommonTechStack
	IsirmtWork = &Q.IsirmtWork
	IsirmtWorkClick = &Q.IsirmtWorkClick
	IsirmtWorkImage = &Q.IsirmtWorkImage
	IsirmtWorkTechStack = &Q.IsirmtWorkTechStack
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                  db,
		CommonImage:         newCommonImage(db, opts...),
		CommonTechStack:     newCommonTechStack(db, opts...),
		IsirmtWork:          newIsirmtWork(db, opts...),
		IsirmtWorkClick:     newIsirmtWorkClick(db, opts...),
		IsirmtWorkImage:     newIsirmtWorkImage(db, opts...),
		IsirmtWorkTechStack: newIsirmtWorkTechStack(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	CommonImage         commonImage
	CommonTechStack     commonTechStack
	IsirmtWork          isirmtWork
	IsirmtWorkClick     isirmtWorkClick
	IsirmtWorkImage     isirmtWorkImage
	IsirmtWorkTechStack isirmtWorkTechStack
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		CommonImage:         q.CommonImage.clone(db),
		CommonTechStack:     q.CommonTechStack.clone(db),
		IsirmtWork:          q.IsirmtWork.clone(db),
		IsirmtWorkClick:     q.IsirmtWorkClick.clone(db),
		IsirmtWorkImage:     q.IsirmtWorkImage.clone(db),
		IsirmtWorkTechStack: q.IsirmtWorkTechStack.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		CommonImage:         q.CommonImage.replaceDB(db),
		CommonTechStack:     q.CommonTechStack.replaceDB(db),
		IsirmtWork:          q.IsirmtWork.replaceDB(db),
		IsirmtWorkClick:     q.IsirmtWorkClick.replaceDB(db),
		IsirmtWorkImage:     q.IsirmtWorkImage.replaceDB(db),
		IsirmtWorkTechStack: q.IsirmtWorkTechStack.replaceDB(db),
	}
}

type queryCtx struct {
	CommonImage         ICommonImageDo
	CommonTechStack     ICommonTechStackDo
	IsirmtWork          IIsirmtWorkDo
	IsirmtWorkClick     IIsirmtWorkClickDo
	IsirmtWorkImage     IIsirmtWorkImageDo
	IsirmtWorkTechStack IIsirmtWorkTechStackDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		CommonImage:         q.CommonImage.WithContext(ctx),
		CommonTechStack:     q.CommonTechStack.WithContext(ctx),
		IsirmtWork:          q.IsirmtWork.WithContext(ctx),
		IsirmtWorkClick:     q.IsirmtWorkClick.WithContext(ctx),
		IsirmtWorkImage:     q.IsirmtWorkImage.WithContext(ctx),
		IsirmtWorkTechStack: q.IsirmtWorkTechStack.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
