// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"realtime/internal/query/model"
)

func newIsirmtWorkURL(db *gorm.DB, opts ...gen.DOOption) isirmtWorkURL {
	_isirmtWorkURL := isirmtWorkURL{}

	_isirmtWorkURL.isirmtWorkURLDo.UseDB(db, opts...)
	_isirmtWorkURL.isirmtWorkURLDo.UseModel(&model.IsirmtWorkURL{})

	tableName := _isirmtWorkURL.isirmtWorkURLDo.TableName()
	_isirmtWorkURL.ALL = field.NewAsterisk(tableName)
	_isirmtWorkURL.ID = field.NewString(tableName, "id")
	_isirmtWorkURL.WorkID = field.NewString(tableName, "work_id")
	_isirmtWorkURL.URL = field.NewString(tableName, "url")
	_isirmtWorkURL.Label = field.NewString(tableName, "label")
	_isirmtWorkURL.DisplayOrder = field.NewInt32(tableName, "display_order")

	_isirmtWorkURL.fillFieldMap()

	return _isirmtWorkURL
}

type isirmtWorkURL struct {
	isirmtWorkURLDo isirmtWorkURLDo

	ALL          field.Asterisk
	ID           field.String
	WorkID       field.String
	URL          field.String
	Label        field.String
	DisplayOrder field.Int32

	fieldMap map[string]field.Expr
}

func (i isirmtWorkURL) Table(newTableName string) *isirmtWorkURL {
	i.isirmtWorkURLDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i isirmtWorkURL) As(alias string) *isirmtWorkURL {
	i.isirmtWorkURLDo.DO = *(i.isirmtWorkURLDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *isirmtWorkURL) updateTableName(table string) *isirmtWorkURL {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewString(table, "id")
	i.WorkID = field.NewString(table, "work_id")
	i.URL = field.NewString(table, "url")
	i.Label = field.NewString(table, "label")
	i.DisplayOrder = field.NewInt32(table, "display_order")

	i.fillFieldMap()

	return i
}

func (i *isirmtWorkURL) WithContext(ctx context.Context) IIsirmtWorkURLDo {
	return i.isirmtWorkURLDo.WithContext(ctx)
}

func (i isirmtWorkURL) TableName() string { return i.isirmtWorkURLDo.TableName() }

func (i isirmtWorkURL) Alias() string { return i.isirmtWorkURLDo.Alias() }

func (i isirmtWorkURL) Columns(cols ...field.Expr) gen.Columns {
	return i.isirmtWorkURLDo.Columns(cols...)
}

func (i *isirmtWorkURL) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *isirmtWorkURL) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 5)
	i.fieldMap["id"] = i.ID
	i.fieldMap["work_id"] = i.WorkID
	i.fieldMap["url"] = i.URL
	i.fieldMap["label"] = i.Label
	i.fieldMap["display_order"] = i.DisplayOrder
}

func (i isirmtWorkURL) clone(db *gorm.DB) isirmtWorkURL {
	i.isirmtWorkURLDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i isirmtWorkURL) replaceDB(db *gorm.DB) isirmtWorkURL {
	i.isirmtWorkURLDo.ReplaceDB(db)
	return i
}

type isirmtWorkURLDo struct{ gen.DO }

type IIsirmtWorkURLDo interface {
	gen.SubQuery
	Debug() IIsirmtWorkURLDo
	WithContext(ctx context.Context) IIsirmtWorkURLDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IIsirmtWorkURLDo
	WriteDB() IIsirmtWorkURLDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IIsirmtWorkURLDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IIsirmtWorkURLDo
	Not(conds ...gen.Condition) IIsirmtWorkURLDo
	Or(conds ...gen.Condition) IIsirmtWorkURLDo
	Select(conds ...field.Expr) IIsirmtWorkURLDo
	Where(conds ...gen.Condition) IIsirmtWorkURLDo
	Order(conds ...field.Expr) IIsirmtWorkURLDo
	Distinct(cols ...field.Expr) IIsirmtWorkURLDo
	Omit(cols ...field.Expr) IIsirmtWorkURLDo
	Join(table schema.Tabler, on ...field.Expr) IIsirmtWorkURLDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IIsirmtWorkURLDo
	RightJoin(table schema.Tabler, on ...field.Expr) IIsirmtWorkURLDo
	Group(cols ...field.Expr) IIsirmtWorkURLDo
	Having(conds ...gen.Condition) IIsirmtWorkURLDo
	Limit(limit int) IIsirmtWorkURLDo
	Offset(offset int) IIsirmtWorkURLDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IIsirmtWorkURLDo
	Unscoped() IIsirmtWorkURLDo
	Create(values ...*model.IsirmtWorkURL) error
	CreateInBatches(values []*model.IsirmtWorkURL, batchSize int) error
	Save(values ...*model.IsirmtWorkURL) error
	First() (*model.IsirmtWorkURL, error)
	Take() (*model.IsirmtWorkURL, error)
	Last() (*model.IsirmtWorkURL, error)
	Find() ([]*model.IsirmtWorkURL, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IsirmtWorkURL, err error)
	FindInBatches(result *[]*model.IsirmtWorkURL, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.IsirmtWorkURL) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IIsirmtWorkURLDo
	Assign(attrs ...field.AssignExpr) IIsirmtWorkURLDo
	Joins(fields ...field.RelationField) IIsirmtWorkURLDo
	Preload(fields ...field.RelationField) IIsirmtWorkURLDo
	FirstOrInit() (*model.IsirmtWorkURL, error)
	FirstOrCreate() (*model.IsirmtWorkURL, error)
	FindByPage(offset int, limit int) (result []*model.IsirmtWorkURL, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IIsirmtWorkURLDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i isirmtWorkURLDo) Debug() IIsirmtWorkURLDo {
	return i.withDO(i.DO.Debug())
}

func (i isirmtWorkURLDo) WithContext(ctx context.Context) IIsirmtWorkURLDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i isirmtWorkURLDo) ReadDB() IIsirmtWorkURLDo {
	return i.Clauses(dbresolver.Read)
}

func (i isirmtWorkURLDo) WriteDB() IIsirmtWorkURLDo {
	return i.Clauses(dbresolver.Write)
}

func (i isirmtWorkURLDo) Session(config *gorm.Session) IIsirmtWorkURLDo {
	return i.withDO(i.DO.Session(config))
}

func (i isirmtWorkURLDo) Clauses(conds ...clause.Expression) IIsirmtWorkURLDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i isirmtWorkURLDo) Returning(value interface{}, columns ...string) IIsirmtWorkURLDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i isirmtWorkURLDo) Not(conds ...gen.Condition) IIsirmtWorkURLDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i isirmtWorkURLDo) Or(conds ...gen.Condition) IIsirmtWorkURLDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i isirmtWorkURLDo) Select(conds ...field.Expr) IIsirmtWorkURLDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i isirmtWorkURLDo) Where(conds ...gen.Condition) IIsirmtWorkURLDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i isirmtWorkURLDo) Order(conds ...field.Expr) IIsirmtWorkURLDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i isirmtWorkURLDo) Distinct(cols ...field.Expr) IIsirmtWorkURLDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i isirmtWorkURLDo) Omit(cols ...field.Expr) IIsirmtWorkURLDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i isirmtWorkURLDo) Join(table schema.Tabler, on ...field.Expr) IIsirmtWorkURLDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i isirmtWorkURLDo) LeftJoin(table schema.Tabler, on ...field.Expr) IIsirmtWorkURLDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i isirmtWorkURLDo) RightJoin(table schema.Tabler, on ...field.Expr) IIsirmtWorkURLDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i isirmtWorkURLDo) Group(cols ...field.Expr) IIsirmtWorkURLDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i isirmtWorkURLDo) Having(conds ...gen.Condition) IIsirmtWorkURLDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i isirmtWorkURLDo) Limit(limit int) IIsirmtWorkURLDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i isirmtWorkURLDo) Offset(offset int) IIsirmtWorkURLDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i isirmtWorkURLDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IIsirmtWorkURLDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i isirmtWorkURLDo) Unscoped() IIsirmtWorkURLDo {
	return i.withDO(i.DO.Unscoped())
}

func (i isirmtWorkURLDo) Create(values ...*model.IsirmtWorkURL) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i isirmtWorkURLDo) CreateInBatches(values []*model.IsirmtWorkURL, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i isirmtWorkURLDo) Save(values ...*model.IsirmtWorkURL) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i isirmtWorkURLDo) First() (*model.IsirmtWorkURL, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWorkURL), nil
	}
}

func (i isirmtWorkURLDo) Take() (*model.IsirmtWorkURL, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWorkURL), nil
	}
}

func (i isirmtWorkURLDo) Last() (*model.IsirmtWorkURL, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWorkURL), nil
	}
}

func (i isirmtWorkURLDo) Find() ([]*model.IsirmtWorkURL, error) {
	result, err := i.DO.Find()
	return result.([]*model.IsirmtWorkURL), err
}

func (i isirmtWorkURLDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IsirmtWorkURL, err error) {
	buf := make([]*model.IsirmtWorkURL, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i isirmtWorkURLDo) FindInBatches(result *[]*model.IsirmtWorkURL, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i isirmtWorkURLDo) Attrs(attrs ...field.AssignExpr) IIsirmtWorkURLDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i isirmtWorkURLDo) Assign(attrs ...field.AssignExpr) IIsirmtWorkURLDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i isirmtWorkURLDo) Joins(fields ...field.RelationField) IIsirmtWorkURLDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i isirmtWorkURLDo) Preload(fields ...field.RelationField) IIsirmtWorkURLDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i isirmtWorkURLDo) FirstOrInit() (*model.IsirmtWorkURL, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWorkURL), nil
	}
}

func (i isirmtWorkURLDo) FirstOrCreate() (*model.IsirmtWorkURL, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWorkURL), nil
	}
}

func (i isirmtWorkURLDo) FindByPage(offset int, limit int) (result []*model.IsirmtWorkURL, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i isirmtWorkURLDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i isirmtWorkURLDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i isirmtWorkURLDo) Delete(models ...*model.IsirmtWorkURL) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *isirmtWorkURLDo) withDO(do gen.Dao) *isirmtWorkURLDo {
	i.DO = *do.(*gen.DO)
	return i
}
