// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"realtime/internal/query/model"
)

func newIsirmtWorkClick(db *gorm.DB, opts ...gen.DOOption) isirmtWorkClick {
	_isirmtWorkClick := isirmtWorkClick{}

	_isirmtWorkClick.isirmtWorkClickDo.UseDB(db, opts...)
	_isirmtWorkClick.isirmtWorkClickDo.UseModel(&model.IsirmtWorkClick{})

	tableName := _isirmtWorkClick.isirmtWorkClickDo.TableName()
	_isirmtWorkClick.ALL = field.NewAsterisk(tableName)
	_isirmtWorkClick.ID = field.NewString(tableName, "id")
	_isirmtWorkClick.WorkID = field.NewString(tableName, "work_id")
	_isirmtWorkClick.ClickedAt = field.NewTime(tableName, "clicked_at")

	_isirmtWorkClick.fillFieldMap()

	return _isirmtWorkClick
}

type isirmtWorkClick struct {
	isirmtWorkClickDo isirmtWorkClickDo

	ALL       field.Asterisk
	ID        field.String
	WorkID    field.String
	ClickedAt field.Time

	fieldMap map[string]field.Expr
}

func (i isirmtWorkClick) Table(newTableName string) *isirmtWorkClick {
	i.isirmtWorkClickDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i isirmtWorkClick) As(alias string) *isirmtWorkClick {
	i.isirmtWorkClickDo.DO = *(i.isirmtWorkClickDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *isirmtWorkClick) updateTableName(table string) *isirmtWorkClick {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewString(table, "id")
	i.WorkID = field.NewString(table, "work_id")
	i.ClickedAt = field.NewTime(table, "clicked_at")

	i.fillFieldMap()

	return i
}

func (i *isirmtWorkClick) WithContext(ctx context.Context) IIsirmtWorkClickDo {
	return i.isirmtWorkClickDo.WithContext(ctx)
}

func (i isirmtWorkClick) TableName() string { return i.isirmtWorkClickDo.TableName() }

func (i isirmtWorkClick) Alias() string { return i.isirmtWorkClickDo.Alias() }

func (i isirmtWorkClick) Columns(cols ...field.Expr) gen.Columns {
	return i.isirmtWorkClickDo.Columns(cols...)
}

func (i *isirmtWorkClick) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *isirmtWorkClick) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 3)
	i.fieldMap["id"] = i.ID
	i.fieldMap["work_id"] = i.WorkID
	i.fieldMap["clicked_at"] = i.ClickedAt
}

func (i isirmtWorkClick) clone(db *gorm.DB) isirmtWorkClick {
	i.isirmtWorkClickDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i isirmtWorkClick) replaceDB(db *gorm.DB) isirmtWorkClick {
	i.isirmtWorkClickDo.ReplaceDB(db)
	return i
}

type isirmtWorkClickDo struct{ gen.DO }

type IIsirmtWorkClickDo interface {
	gen.SubQuery
	Debug() IIsirmtWorkClickDo
	WithContext(ctx context.Context) IIsirmtWorkClickDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IIsirmtWorkClickDo
	WriteDB() IIsirmtWorkClickDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IIsirmtWorkClickDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IIsirmtWorkClickDo
	Not(conds ...gen.Condition) IIsirmtWorkClickDo
	Or(conds ...gen.Condition) IIsirmtWorkClickDo
	Select(conds ...field.Expr) IIsirmtWorkClickDo
	Where(conds ...gen.Condition) IIsirmtWorkClickDo
	Order(conds ...field.Expr) IIsirmtWorkClickDo
	Distinct(cols ...field.Expr) IIsirmtWorkClickDo
	Omit(cols ...field.Expr) IIsirmtWorkClickDo
	Join(table schema.Tabler, on ...field.Expr) IIsirmtWorkClickDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IIsirmtWorkClickDo
	RightJoin(table schema.Tabler, on ...field.Expr) IIsirmtWorkClickDo
	Group(cols ...field.Expr) IIsirmtWorkClickDo
	Having(conds ...gen.Condition) IIsirmtWorkClickDo
	Limit(limit int) IIsirmtWorkClickDo
	Offset(offset int) IIsirmtWorkClickDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IIsirmtWorkClickDo
	Unscoped() IIsirmtWorkClickDo
	Create(values ...*model.IsirmtWorkClick) error
	CreateInBatches(values []*model.IsirmtWorkClick, batchSize int) error
	Save(values ...*model.IsirmtWorkClick) error
	First() (*model.IsirmtWorkClick, error)
	Take() (*model.IsirmtWorkClick, error)
	Last() (*model.IsirmtWorkClick, error)
	Find() ([]*model.IsirmtWorkClick, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IsirmtWorkClick, err error)
	FindInBatches(result *[]*model.IsirmtWorkClick, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.IsirmtWorkClick) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IIsirmtWorkClickDo
	Assign(attrs ...field.AssignExpr) IIsirmtWorkClickDo
	Joins(fields ...field.RelationField) IIsirmtWorkClickDo
	Preload(fields ...field.RelationField) IIsirmtWorkClickDo
	FirstOrInit() (*model.IsirmtWorkClick, error)
	FirstOrCreate() (*model.IsirmtWorkClick, error)
	FindByPage(offset int, limit int) (result []*model.IsirmtWorkClick, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IIsirmtWorkClickDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i isirmtWorkClickDo) Debug() IIsirmtWorkClickDo {
	return i.withDO(i.DO.Debug())
}

func (i isirmtWorkClickDo) WithContext(ctx context.Context) IIsirmtWorkClickDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i isirmtWorkClickDo) ReadDB() IIsirmtWorkClickDo {
	return i.Clauses(dbresolver.Read)
}

func (i isirmtWorkClickDo) WriteDB() IIsirmtWorkClickDo {
	return i.Clauses(dbresolver.Write)
}

func (i isirmtWorkClickDo) Session(config *gorm.Session) IIsirmtWorkClickDo {
	return i.withDO(i.DO.Session(config))
}

func (i isirmtWorkClickDo) Clauses(conds ...clause.Expression) IIsirmtWorkClickDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i isirmtWorkClickDo) Returning(value interface{}, columns ...string) IIsirmtWorkClickDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i isirmtWorkClickDo) Not(conds ...gen.Condition) IIsirmtWorkClickDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i isirmtWorkClickDo) Or(conds ...gen.Condition) IIsirmtWorkClickDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i isirmtWorkClickDo) Select(conds ...field.Expr) IIsirmtWorkClickDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i isirmtWorkClickDo) Where(conds ...gen.Condition) IIsirmtWorkClickDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i isirmtWorkClickDo) Order(conds ...field.Expr) IIsirmtWorkClickDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i isirmtWorkClickDo) Distinct(cols ...field.Expr) IIsirmtWorkClickDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i isirmtWorkClickDo) Omit(cols ...field.Expr) IIsirmtWorkClickDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i isirmtWorkClickDo) Join(table schema.Tabler, on ...field.Expr) IIsirmtWorkClickDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i isirmtWorkClickDo) LeftJoin(table schema.Tabler, on ...field.Expr) IIsirmtWorkClickDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i isirmtWorkClickDo) RightJoin(table schema.Tabler, on ...field.Expr) IIsirmtWorkClickDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i isirmtWorkClickDo) Group(cols ...field.Expr) IIsirmtWorkClickDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i isirmtWorkClickDo) Having(conds ...gen.Condition) IIsirmtWorkClickDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i isirmtWorkClickDo) Limit(limit int) IIsirmtWorkClickDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i isirmtWorkClickDo) Offset(offset int) IIsirmtWorkClickDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i isirmtWorkClickDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IIsirmtWorkClickDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i isirmtWorkClickDo) Unscoped() IIsirmtWorkClickDo {
	return i.withDO(i.DO.Unscoped())
}

func (i isirmtWorkClickDo) Create(values ...*model.IsirmtWorkClick) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i isirmtWorkClickDo) CreateInBatches(values []*model.IsirmtWorkClick, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i isirmtWorkClickDo) Save(values ...*model.IsirmtWorkClick) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i isirmtWorkClickDo) First() (*model.IsirmtWorkClick, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWorkClick), nil
	}
}

func (i isirmtWorkClickDo) Take() (*model.IsirmtWorkClick, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWorkClick), nil
	}
}

func (i isirmtWorkClickDo) Last() (*model.IsirmtWorkClick, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWorkClick), nil
	}
}

func (i isirmtWorkClickDo) Find() ([]*model.IsirmtWorkClick, error) {
	result, err := i.DO.Find()
	return result.([]*model.IsirmtWorkClick), err
}

func (i isirmtWorkClickDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IsirmtWorkClick, err error) {
	buf := make([]*model.IsirmtWorkClick, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i isirmtWorkClickDo) FindInBatches(result *[]*model.IsirmtWorkClick, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i isirmtWorkClickDo) Attrs(attrs ...field.AssignExpr) IIsirmtWorkClickDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i isirmtWorkClickDo) Assign(attrs ...field.AssignExpr) IIsirmtWorkClickDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i isirmtWorkClickDo) Joins(fields ...field.RelationField) IIsirmtWorkClickDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i isirmtWorkClickDo) Preload(fields ...field.RelationField) IIsirmtWorkClickDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i isirmtWorkClickDo) FirstOrInit() (*model.IsirmtWorkClick, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWorkClick), nil
	}
}

func (i isirmtWorkClickDo) FirstOrCreate() (*model.IsirmtWorkClick, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWorkClick), nil
	}
}

func (i isirmtWorkClickDo) FindByPage(offset int, limit int) (result []*model.IsirmtWorkClick, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i isirmtWorkClickDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i isirmtWorkClickDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i isirmtWorkClickDo) Delete(models ...*model.IsirmtWorkClick) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *isirmtWorkClickDo) withDO(do gen.Dao) *isirmtWorkClickDo {
	i.DO = *do.(*gen.DO)
	return i
}
