// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"realtime/internal/query/model"
)

func newIsirmtWork(db *gorm.DB, opts ...gen.DOOption) isirmtWork {
	_isirmtWork := isirmtWork{}

	_isirmtWork.isirmtWorkDo.UseDB(db, opts...)
	_isirmtWork.isirmtWorkDo.UseModel(&model.IsirmtWork{})

	tableName := _isirmtWork.isirmtWorkDo.TableName()
	_isirmtWork.ALL = field.NewAsterisk(tableName)
	_isirmtWork.ID = field.NewString(tableName, "id")
	_isirmtWork.Slug = field.NewString(tableName, "slug")
	_isirmtWork.Title = field.NewString(tableName, "title")
	_isirmtWork.Comment = field.NewString(tableName, "comment")
	_isirmtWork.CreatedAt = field.NewTime(tableName, "created_at")
	_isirmtWork.AccentColor = field.NewString(tableName, "accent_color")
	_isirmtWork.Description = field.NewString(tableName, "description")
	_isirmtWork.IsPublic = field.NewBool(tableName, "is_public")
	_isirmtWork.ThumbnailImageID = field.NewString(tableName, "thumbnail_image_id")

	_isirmtWork.fillFieldMap()

	return _isirmtWork
}

type isirmtWork struct {
	isirmtWorkDo isirmtWorkDo

	ALL              field.Asterisk
	ID               field.String
	Slug             field.String
	Title            field.String
	Comment          field.String
	CreatedAt        field.Time
	AccentColor      field.String
	Description      field.String
	IsPublic         field.Bool
	ThumbnailImageID field.String

	fieldMap map[string]field.Expr
}

func (i isirmtWork) Table(newTableName string) *isirmtWork {
	i.isirmtWorkDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i isirmtWork) As(alias string) *isirmtWork {
	i.isirmtWorkDo.DO = *(i.isirmtWorkDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *isirmtWork) updateTableName(table string) *isirmtWork {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewString(table, "id")
	i.Slug = field.NewString(table, "slug")
	i.Title = field.NewString(table, "title")
	i.Comment = field.NewString(table, "comment")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.AccentColor = field.NewString(table, "accent_color")
	i.Description = field.NewString(table, "description")
	i.IsPublic = field.NewBool(table, "is_public")
	i.ThumbnailImageID = field.NewString(table, "thumbnail_image_id")

	i.fillFieldMap()

	return i
}

func (i *isirmtWork) WithContext(ctx context.Context) IIsirmtWorkDo {
	return i.isirmtWorkDo.WithContext(ctx)
}

func (i isirmtWork) TableName() string { return i.isirmtWorkDo.TableName() }

func (i isirmtWork) Alias() string { return i.isirmtWorkDo.Alias() }

func (i isirmtWork) Columns(cols ...field.Expr) gen.Columns { return i.isirmtWorkDo.Columns(cols...) }

func (i *isirmtWork) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *isirmtWork) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 9)
	i.fieldMap["id"] = i.ID
	i.fieldMap["slug"] = i.Slug
	i.fieldMap["title"] = i.Title
	i.fieldMap["comment"] = i.Comment
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["accent_color"] = i.AccentColor
	i.fieldMap["description"] = i.Description
	i.fieldMap["is_public"] = i.IsPublic
	i.fieldMap["thumbnail_image_id"] = i.ThumbnailImageID
}

func (i isirmtWork) clone(db *gorm.DB) isirmtWork {
	i.isirmtWorkDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i isirmtWork) replaceDB(db *gorm.DB) isirmtWork {
	i.isirmtWorkDo.ReplaceDB(db)
	return i
}

type isirmtWorkDo struct{ gen.DO }

type IIsirmtWorkDo interface {
	gen.SubQuery
	Debug() IIsirmtWorkDo
	WithContext(ctx context.Context) IIsirmtWorkDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IIsirmtWorkDo
	WriteDB() IIsirmtWorkDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IIsirmtWorkDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IIsirmtWorkDo
	Not(conds ...gen.Condition) IIsirmtWorkDo
	Or(conds ...gen.Condition) IIsirmtWorkDo
	Select(conds ...field.Expr) IIsirmtWorkDo
	Where(conds ...gen.Condition) IIsirmtWorkDo
	Order(conds ...field.Expr) IIsirmtWorkDo
	Distinct(cols ...field.Expr) IIsirmtWorkDo
	Omit(cols ...field.Expr) IIsirmtWorkDo
	Join(table schema.Tabler, on ...field.Expr) IIsirmtWorkDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IIsirmtWorkDo
	RightJoin(table schema.Tabler, on ...field.Expr) IIsirmtWorkDo
	Group(cols ...field.Expr) IIsirmtWorkDo
	Having(conds ...gen.Condition) IIsirmtWorkDo
	Limit(limit int) IIsirmtWorkDo
	Offset(offset int) IIsirmtWorkDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IIsirmtWorkDo
	Unscoped() IIsirmtWorkDo
	Create(values ...*model.IsirmtWork) error
	CreateInBatches(values []*model.IsirmtWork, batchSize int) error
	Save(values ...*model.IsirmtWork) error
	First() (*model.IsirmtWork, error)
	Take() (*model.IsirmtWork, error)
	Last() (*model.IsirmtWork, error)
	Find() ([]*model.IsirmtWork, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IsirmtWork, err error)
	FindInBatches(result *[]*model.IsirmtWork, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.IsirmtWork) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IIsirmtWorkDo
	Assign(attrs ...field.AssignExpr) IIsirmtWorkDo
	Joins(fields ...field.RelationField) IIsirmtWorkDo
	Preload(fields ...field.RelationField) IIsirmtWorkDo
	FirstOrInit() (*model.IsirmtWork, error)
	FirstOrCreate() (*model.IsirmtWork, error)
	FindByPage(offset int, limit int) (result []*model.IsirmtWork, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IIsirmtWorkDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i isirmtWorkDo) Debug() IIsirmtWorkDo {
	return i.withDO(i.DO.Debug())
}

func (i isirmtWorkDo) WithContext(ctx context.Context) IIsirmtWorkDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i isirmtWorkDo) ReadDB() IIsirmtWorkDo {
	return i.Clauses(dbresolver.Read)
}

func (i isirmtWorkDo) WriteDB() IIsirmtWorkDo {
	return i.Clauses(dbresolver.Write)
}

func (i isirmtWorkDo) Session(config *gorm.Session) IIsirmtWorkDo {
	return i.withDO(i.DO.Session(config))
}

func (i isirmtWorkDo) Clauses(conds ...clause.Expression) IIsirmtWorkDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i isirmtWorkDo) Returning(value interface{}, columns ...string) IIsirmtWorkDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i isirmtWorkDo) Not(conds ...gen.Condition) IIsirmtWorkDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i isirmtWorkDo) Or(conds ...gen.Condition) IIsirmtWorkDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i isirmtWorkDo) Select(conds ...field.Expr) IIsirmtWorkDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i isirmtWorkDo) Where(conds ...gen.Condition) IIsirmtWorkDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i isirmtWorkDo) Order(conds ...field.Expr) IIsirmtWorkDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i isirmtWorkDo) Distinct(cols ...field.Expr) IIsirmtWorkDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i isirmtWorkDo) Omit(cols ...field.Expr) IIsirmtWorkDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i isirmtWorkDo) Join(table schema.Tabler, on ...field.Expr) IIsirmtWorkDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i isirmtWorkDo) LeftJoin(table schema.Tabler, on ...field.Expr) IIsirmtWorkDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i isirmtWorkDo) RightJoin(table schema.Tabler, on ...field.Expr) IIsirmtWorkDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i isirmtWorkDo) Group(cols ...field.Expr) IIsirmtWorkDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i isirmtWorkDo) Having(conds ...gen.Condition) IIsirmtWorkDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i isirmtWorkDo) Limit(limit int) IIsirmtWorkDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i isirmtWorkDo) Offset(offset int) IIsirmtWorkDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i isirmtWorkDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IIsirmtWorkDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i isirmtWorkDo) Unscoped() IIsirmtWorkDo {
	return i.withDO(i.DO.Unscoped())
}

func (i isirmtWorkDo) Create(values ...*model.IsirmtWork) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i isirmtWorkDo) CreateInBatches(values []*model.IsirmtWork, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i isirmtWorkDo) Save(values ...*model.IsirmtWork) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i isirmtWorkDo) First() (*model.IsirmtWork, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWork), nil
	}
}

func (i isirmtWorkDo) Take() (*model.IsirmtWork, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWork), nil
	}
}

func (i isirmtWorkDo) Last() (*model.IsirmtWork, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWork), nil
	}
}

func (i isirmtWorkDo) Find() ([]*model.IsirmtWork, error) {
	result, err := i.DO.Find()
	return result.([]*model.IsirmtWork), err
}

func (i isirmtWorkDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IsirmtWork, err error) {
	buf := make([]*model.IsirmtWork, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i isirmtWorkDo) FindInBatches(result *[]*model.IsirmtWork, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i isirmtWorkDo) Attrs(attrs ...field.AssignExpr) IIsirmtWorkDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i isirmtWorkDo) Assign(attrs ...field.AssignExpr) IIsirmtWorkDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i isirmtWorkDo) Joins(fields ...field.RelationField) IIsirmtWorkDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i isirmtWorkDo) Preload(fields ...field.RelationField) IIsirmtWorkDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i isirmtWorkDo) FirstOrInit() (*model.IsirmtWork, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWork), nil
	}
}

func (i isirmtWorkDo) FirstOrCreate() (*model.IsirmtWork, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWork), nil
	}
}

func (i isirmtWorkDo) FindByPage(offset int, limit int) (result []*model.IsirmtWork, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i isirmtWorkDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i isirmtWorkDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i isirmtWorkDo) Delete(models ...*model.IsirmtWork) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *isirmtWorkDo) withDO(do gen.Dao) *isirmtWorkDo {
	i.DO = *do.(*gen.DO)
	return i
}
