// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"realtime/internal/query/model"
)

func newIsirmtWorkImage(db *gorm.DB, opts ...gen.DOOption) isirmtWorkImage {
	_isirmtWorkImage := isirmtWorkImage{}

	_isirmtWorkImage.isirmtWorkImageDo.UseDB(db, opts...)
	_isirmtWorkImage.isirmtWorkImageDo.UseModel(&model.IsirmtWorkImage{})

	tableName := _isirmtWorkImage.isirmtWorkImageDo.TableName()
	_isirmtWorkImage.ALL = field.NewAsterisk(tableName)
	_isirmtWorkImage.ID = field.NewString(tableName, "id")
	_isirmtWorkImage.WorkID = field.NewString(tableName, "work_id")
	_isirmtWorkImage.ImageID = field.NewString(tableName, "image_id")
	_isirmtWorkImage.DisplayOrder = field.NewInt32(tableName, "display_order")

	_isirmtWorkImage.fillFieldMap()

	return _isirmtWorkImage
}

type isirmtWorkImage struct {
	isirmtWorkImageDo isirmtWorkImageDo

	ALL          field.Asterisk
	ID           field.String
	WorkID       field.String
	ImageID      field.String
	DisplayOrder field.Int32

	fieldMap map[string]field.Expr
}

func (i isirmtWorkImage) Table(newTableName string) *isirmtWorkImage {
	i.isirmtWorkImageDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i isirmtWorkImage) As(alias string) *isirmtWorkImage {
	i.isirmtWorkImageDo.DO = *(i.isirmtWorkImageDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *isirmtWorkImage) updateTableName(table string) *isirmtWorkImage {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewString(table, "id")
	i.WorkID = field.NewString(table, "work_id")
	i.ImageID = field.NewString(table, "image_id")
	i.DisplayOrder = field.NewInt32(table, "display_order")

	i.fillFieldMap()

	return i
}

func (i *isirmtWorkImage) WithContext(ctx context.Context) IIsirmtWorkImageDo {
	return i.isirmtWorkImageDo.WithContext(ctx)
}

func (i isirmtWorkImage) TableName() string { return i.isirmtWorkImageDo.TableName() }

func (i isirmtWorkImage) Alias() string { return i.isirmtWorkImageDo.Alias() }

func (i isirmtWorkImage) Columns(cols ...field.Expr) gen.Columns {
	return i.isirmtWorkImageDo.Columns(cols...)
}

func (i *isirmtWorkImage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *isirmtWorkImage) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 4)
	i.fieldMap["id"] = i.ID
	i.fieldMap["work_id"] = i.WorkID
	i.fieldMap["image_id"] = i.ImageID
	i.fieldMap["display_order"] = i.DisplayOrder
}

func (i isirmtWorkImage) clone(db *gorm.DB) isirmtWorkImage {
	i.isirmtWorkImageDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i isirmtWorkImage) replaceDB(db *gorm.DB) isirmtWorkImage {
	i.isirmtWorkImageDo.ReplaceDB(db)
	return i
}

type isirmtWorkImageDo struct{ gen.DO }

type IIsirmtWorkImageDo interface {
	gen.SubQuery
	Debug() IIsirmtWorkImageDo
	WithContext(ctx context.Context) IIsirmtWorkImageDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IIsirmtWorkImageDo
	WriteDB() IIsirmtWorkImageDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IIsirmtWorkImageDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IIsirmtWorkImageDo
	Not(conds ...gen.Condition) IIsirmtWorkImageDo
	Or(conds ...gen.Condition) IIsirmtWorkImageDo
	Select(conds ...field.Expr) IIsirmtWorkImageDo
	Where(conds ...gen.Condition) IIsirmtWorkImageDo
	Order(conds ...field.Expr) IIsirmtWorkImageDo
	Distinct(cols ...field.Expr) IIsirmtWorkImageDo
	Omit(cols ...field.Expr) IIsirmtWorkImageDo
	Join(table schema.Tabler, on ...field.Expr) IIsirmtWorkImageDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IIsirmtWorkImageDo
	RightJoin(table schema.Tabler, on ...field.Expr) IIsirmtWorkImageDo
	Group(cols ...field.Expr) IIsirmtWorkImageDo
	Having(conds ...gen.Condition) IIsirmtWorkImageDo
	Limit(limit int) IIsirmtWorkImageDo
	Offset(offset int) IIsirmtWorkImageDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IIsirmtWorkImageDo
	Unscoped() IIsirmtWorkImageDo
	Create(values ...*model.IsirmtWorkImage) error
	CreateInBatches(values []*model.IsirmtWorkImage, batchSize int) error
	Save(values ...*model.IsirmtWorkImage) error
	First() (*model.IsirmtWorkImage, error)
	Take() (*model.IsirmtWorkImage, error)
	Last() (*model.IsirmtWorkImage, error)
	Find() ([]*model.IsirmtWorkImage, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IsirmtWorkImage, err error)
	FindInBatches(result *[]*model.IsirmtWorkImage, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.IsirmtWorkImage) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IIsirmtWorkImageDo
	Assign(attrs ...field.AssignExpr) IIsirmtWorkImageDo
	Joins(fields ...field.RelationField) IIsirmtWorkImageDo
	Preload(fields ...field.RelationField) IIsirmtWorkImageDo
	FirstOrInit() (*model.IsirmtWorkImage, error)
	FirstOrCreate() (*model.IsirmtWorkImage, error)
	FindByPage(offset int, limit int) (result []*model.IsirmtWorkImage, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IIsirmtWorkImageDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i isirmtWorkImageDo) Debug() IIsirmtWorkImageDo {
	return i.withDO(i.DO.Debug())
}

func (i isirmtWorkImageDo) WithContext(ctx context.Context) IIsirmtWorkImageDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i isirmtWorkImageDo) ReadDB() IIsirmtWorkImageDo {
	return i.Clauses(dbresolver.Read)
}

func (i isirmtWorkImageDo) WriteDB() IIsirmtWorkImageDo {
	return i.Clauses(dbresolver.Write)
}

func (i isirmtWorkImageDo) Session(config *gorm.Session) IIsirmtWorkImageDo {
	return i.withDO(i.DO.Session(config))
}

func (i isirmtWorkImageDo) Clauses(conds ...clause.Expression) IIsirmtWorkImageDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i isirmtWorkImageDo) Returning(value interface{}, columns ...string) IIsirmtWorkImageDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i isirmtWorkImageDo) Not(conds ...gen.Condition) IIsirmtWorkImageDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i isirmtWorkImageDo) Or(conds ...gen.Condition) IIsirmtWorkImageDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i isirmtWorkImageDo) Select(conds ...field.Expr) IIsirmtWorkImageDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i isirmtWorkImageDo) Where(conds ...gen.Condition) IIsirmtWorkImageDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i isirmtWorkImageDo) Order(conds ...field.Expr) IIsirmtWorkImageDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i isirmtWorkImageDo) Distinct(cols ...field.Expr) IIsirmtWorkImageDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i isirmtWorkImageDo) Omit(cols ...field.Expr) IIsirmtWorkImageDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i isirmtWorkImageDo) Join(table schema.Tabler, on ...field.Expr) IIsirmtWorkImageDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i isirmtWorkImageDo) LeftJoin(table schema.Tabler, on ...field.Expr) IIsirmtWorkImageDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i isirmtWorkImageDo) RightJoin(table schema.Tabler, on ...field.Expr) IIsirmtWorkImageDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i isirmtWorkImageDo) Group(cols ...field.Expr) IIsirmtWorkImageDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i isirmtWorkImageDo) Having(conds ...gen.Condition) IIsirmtWorkImageDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i isirmtWorkImageDo) Limit(limit int) IIsirmtWorkImageDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i isirmtWorkImageDo) Offset(offset int) IIsirmtWorkImageDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i isirmtWorkImageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IIsirmtWorkImageDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i isirmtWorkImageDo) Unscoped() IIsirmtWorkImageDo {
	return i.withDO(i.DO.Unscoped())
}

func (i isirmtWorkImageDo) Create(values ...*model.IsirmtWorkImage) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i isirmtWorkImageDo) CreateInBatches(values []*model.IsirmtWorkImage, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i isirmtWorkImageDo) Save(values ...*model.IsirmtWorkImage) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i isirmtWorkImageDo) First() (*model.IsirmtWorkImage, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWorkImage), nil
	}
}

func (i isirmtWorkImageDo) Take() (*model.IsirmtWorkImage, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWorkImage), nil
	}
}

func (i isirmtWorkImageDo) Last() (*model.IsirmtWorkImage, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWorkImage), nil
	}
}

func (i isirmtWorkImageDo) Find() ([]*model.IsirmtWorkImage, error) {
	result, err := i.DO.Find()
	return result.([]*model.IsirmtWorkImage), err
}

func (i isirmtWorkImageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IsirmtWorkImage, err error) {
	buf := make([]*model.IsirmtWorkImage, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i isirmtWorkImageDo) FindInBatches(result *[]*model.IsirmtWorkImage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i isirmtWorkImageDo) Attrs(attrs ...field.AssignExpr) IIsirmtWorkImageDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i isirmtWorkImageDo) Assign(attrs ...field.AssignExpr) IIsirmtWorkImageDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i isirmtWorkImageDo) Joins(fields ...field.RelationField) IIsirmtWorkImageDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i isirmtWorkImageDo) Preload(fields ...field.RelationField) IIsirmtWorkImageDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i isirmtWorkImageDo) FirstOrInit() (*model.IsirmtWorkImage, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWorkImage), nil
	}
}

func (i isirmtWorkImageDo) FirstOrCreate() (*model.IsirmtWorkImage, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWorkImage), nil
	}
}

func (i isirmtWorkImageDo) FindByPage(offset int, limit int) (result []*model.IsirmtWorkImage, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i isirmtWorkImageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i isirmtWorkImageDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i isirmtWorkImageDo) Delete(models ...*model.IsirmtWorkImage) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *isirmtWorkImageDo) withDO(do gen.Dao) *isirmtWorkImageDo {
	i.DO = *do.(*gen.DO)
	return i
}
