// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"realtime/internal/query/model"
)

func newIsirmtWorkTechStack(db *gorm.DB, opts ...gen.DOOption) isirmtWorkTechStack {
	_isirmtWorkTechStack := isirmtWorkTechStack{}

	_isirmtWorkTechStack.isirmtWorkTechStackDo.UseDB(db, opts...)
	_isirmtWorkTechStack.isirmtWorkTechStackDo.UseModel(&model.IsirmtWorkTechStack{})

	tableName := _isirmtWorkTechStack.isirmtWorkTechStackDo.TableName()
	_isirmtWorkTechStack.ALL = field.NewAsterisk(tableName)
	_isirmtWorkTechStack.ID = field.NewString(tableName, "id")
	_isirmtWorkTechStack.WorkID = field.NewString(tableName, "work_id")
	_isirmtWorkTechStack.TechStackID = field.NewString(tableName, "tech_stack_id")

	_isirmtWorkTechStack.fillFieldMap()

	return _isirmtWorkTechStack
}

type isirmtWorkTechStack struct {
	isirmtWorkTechStackDo isirmtWorkTechStackDo

	ALL         field.Asterisk
	ID          field.String
	WorkID      field.String
	TechStackID field.String

	fieldMap map[string]field.Expr
}

func (i isirmtWorkTechStack) Table(newTableName string) *isirmtWorkTechStack {
	i.isirmtWorkTechStackDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i isirmtWorkTechStack) As(alias string) *isirmtWorkTechStack {
	i.isirmtWorkTechStackDo.DO = *(i.isirmtWorkTechStackDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *isirmtWorkTechStack) updateTableName(table string) *isirmtWorkTechStack {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewString(table, "id")
	i.WorkID = field.NewString(table, "work_id")
	i.TechStackID = field.NewString(table, "tech_stack_id")

	i.fillFieldMap()

	return i
}

func (i *isirmtWorkTechStack) WithContext(ctx context.Context) IIsirmtWorkTechStackDo {
	return i.isirmtWorkTechStackDo.WithContext(ctx)
}

func (i isirmtWorkTechStack) TableName() string { return i.isirmtWorkTechStackDo.TableName() }

func (i isirmtWorkTechStack) Alias() string { return i.isirmtWorkTechStackDo.Alias() }

func (i isirmtWorkTechStack) Columns(cols ...field.Expr) gen.Columns {
	return i.isirmtWorkTechStackDo.Columns(cols...)
}

func (i *isirmtWorkTechStack) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *isirmtWorkTechStack) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 3)
	i.fieldMap["id"] = i.ID
	i.fieldMap["work_id"] = i.WorkID
	i.fieldMap["tech_stack_id"] = i.TechStackID
}

func (i isirmtWorkTechStack) clone(db *gorm.DB) isirmtWorkTechStack {
	i.isirmtWorkTechStackDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i isirmtWorkTechStack) replaceDB(db *gorm.DB) isirmtWorkTechStack {
	i.isirmtWorkTechStackDo.ReplaceDB(db)
	return i
}

type isirmtWorkTechStackDo struct{ gen.DO }

type IIsirmtWorkTechStackDo interface {
	gen.SubQuery
	Debug() IIsirmtWorkTechStackDo
	WithContext(ctx context.Context) IIsirmtWorkTechStackDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IIsirmtWorkTechStackDo
	WriteDB() IIsirmtWorkTechStackDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IIsirmtWorkTechStackDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IIsirmtWorkTechStackDo
	Not(conds ...gen.Condition) IIsirmtWorkTechStackDo
	Or(conds ...gen.Condition) IIsirmtWorkTechStackDo
	Select(conds ...field.Expr) IIsirmtWorkTechStackDo
	Where(conds ...gen.Condition) IIsirmtWorkTechStackDo
	Order(conds ...field.Expr) IIsirmtWorkTechStackDo
	Distinct(cols ...field.Expr) IIsirmtWorkTechStackDo
	Omit(cols ...field.Expr) IIsirmtWorkTechStackDo
	Join(table schema.Tabler, on ...field.Expr) IIsirmtWorkTechStackDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IIsirmtWorkTechStackDo
	RightJoin(table schema.Tabler, on ...field.Expr) IIsirmtWorkTechStackDo
	Group(cols ...field.Expr) IIsirmtWorkTechStackDo
	Having(conds ...gen.Condition) IIsirmtWorkTechStackDo
	Limit(limit int) IIsirmtWorkTechStackDo
	Offset(offset int) IIsirmtWorkTechStackDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IIsirmtWorkTechStackDo
	Unscoped() IIsirmtWorkTechStackDo
	Create(values ...*model.IsirmtWorkTechStack) error
	CreateInBatches(values []*model.IsirmtWorkTechStack, batchSize int) error
	Save(values ...*model.IsirmtWorkTechStack) error
	First() (*model.IsirmtWorkTechStack, error)
	Take() (*model.IsirmtWorkTechStack, error)
	Last() (*model.IsirmtWorkTechStack, error)
	Find() ([]*model.IsirmtWorkTechStack, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IsirmtWorkTechStack, err error)
	FindInBatches(result *[]*model.IsirmtWorkTechStack, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.IsirmtWorkTechStack) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IIsirmtWorkTechStackDo
	Assign(attrs ...field.AssignExpr) IIsirmtWorkTechStackDo
	Joins(fields ...field.RelationField) IIsirmtWorkTechStackDo
	Preload(fields ...field.RelationField) IIsirmtWorkTechStackDo
	FirstOrInit() (*model.IsirmtWorkTechStack, error)
	FirstOrCreate() (*model.IsirmtWorkTechStack, error)
	FindByPage(offset int, limit int) (result []*model.IsirmtWorkTechStack, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IIsirmtWorkTechStackDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i isirmtWorkTechStackDo) Debug() IIsirmtWorkTechStackDo {
	return i.withDO(i.DO.Debug())
}

func (i isirmtWorkTechStackDo) WithContext(ctx context.Context) IIsirmtWorkTechStackDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i isirmtWorkTechStackDo) ReadDB() IIsirmtWorkTechStackDo {
	return i.Clauses(dbresolver.Read)
}

func (i isirmtWorkTechStackDo) WriteDB() IIsirmtWorkTechStackDo {
	return i.Clauses(dbresolver.Write)
}

func (i isirmtWorkTechStackDo) Session(config *gorm.Session) IIsirmtWorkTechStackDo {
	return i.withDO(i.DO.Session(config))
}

func (i isirmtWorkTechStackDo) Clauses(conds ...clause.Expression) IIsirmtWorkTechStackDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i isirmtWorkTechStackDo) Returning(value interface{}, columns ...string) IIsirmtWorkTechStackDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i isirmtWorkTechStackDo) Not(conds ...gen.Condition) IIsirmtWorkTechStackDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i isirmtWorkTechStackDo) Or(conds ...gen.Condition) IIsirmtWorkTechStackDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i isirmtWorkTechStackDo) Select(conds ...field.Expr) IIsirmtWorkTechStackDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i isirmtWorkTechStackDo) Where(conds ...gen.Condition) IIsirmtWorkTechStackDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i isirmtWorkTechStackDo) Order(conds ...field.Expr) IIsirmtWorkTechStackDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i isirmtWorkTechStackDo) Distinct(cols ...field.Expr) IIsirmtWorkTechStackDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i isirmtWorkTechStackDo) Omit(cols ...field.Expr) IIsirmtWorkTechStackDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i isirmtWorkTechStackDo) Join(table schema.Tabler, on ...field.Expr) IIsirmtWorkTechStackDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i isirmtWorkTechStackDo) LeftJoin(table schema.Tabler, on ...field.Expr) IIsirmtWorkTechStackDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i isirmtWorkTechStackDo) RightJoin(table schema.Tabler, on ...field.Expr) IIsirmtWorkTechStackDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i isirmtWorkTechStackDo) Group(cols ...field.Expr) IIsirmtWorkTechStackDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i isirmtWorkTechStackDo) Having(conds ...gen.Condition) IIsirmtWorkTechStackDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i isirmtWorkTechStackDo) Limit(limit int) IIsirmtWorkTechStackDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i isirmtWorkTechStackDo) Offset(offset int) IIsirmtWorkTechStackDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i isirmtWorkTechStackDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IIsirmtWorkTechStackDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i isirmtWorkTechStackDo) Unscoped() IIsirmtWorkTechStackDo {
	return i.withDO(i.DO.Unscoped())
}

func (i isirmtWorkTechStackDo) Create(values ...*model.IsirmtWorkTechStack) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i isirmtWorkTechStackDo) CreateInBatches(values []*model.IsirmtWorkTechStack, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i isirmtWorkTechStackDo) Save(values ...*model.IsirmtWorkTechStack) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i isirmtWorkTechStackDo) First() (*model.IsirmtWorkTechStack, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWorkTechStack), nil
	}
}

func (i isirmtWorkTechStackDo) Take() (*model.IsirmtWorkTechStack, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWorkTechStack), nil
	}
}

func (i isirmtWorkTechStackDo) Last() (*model.IsirmtWorkTechStack, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWorkTechStack), nil
	}
}

func (i isirmtWorkTechStackDo) Find() ([]*model.IsirmtWorkTechStack, error) {
	result, err := i.DO.Find()
	return result.([]*model.IsirmtWorkTechStack), err
}

func (i isirmtWorkTechStackDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IsirmtWorkTechStack, err error) {
	buf := make([]*model.IsirmtWorkTechStack, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i isirmtWorkTechStackDo) FindInBatches(result *[]*model.IsirmtWorkTechStack, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i isirmtWorkTechStackDo) Attrs(attrs ...field.AssignExpr) IIsirmtWorkTechStackDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i isirmtWorkTechStackDo) Assign(attrs ...field.AssignExpr) IIsirmtWorkTechStackDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i isirmtWorkTechStackDo) Joins(fields ...field.RelationField) IIsirmtWorkTechStackDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i isirmtWorkTechStackDo) Preload(fields ...field.RelationField) IIsirmtWorkTechStackDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i isirmtWorkTechStackDo) FirstOrInit() (*model.IsirmtWorkTechStack, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWorkTechStack), nil
	}
}

func (i isirmtWorkTechStackDo) FirstOrCreate() (*model.IsirmtWorkTechStack, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.IsirmtWorkTechStack), nil
	}
}

func (i isirmtWorkTechStackDo) FindByPage(offset int, limit int) (result []*model.IsirmtWorkTechStack, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i isirmtWorkTechStackDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i isirmtWorkTechStackDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i isirmtWorkTechStackDo) Delete(models ...*model.IsirmtWorkTechStack) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *isirmtWorkTechStackDo) withDO(do gen.Dao) *isirmtWorkTechStackDo {
	i.DO = *do.(*gen.DO)
	return i
}
